name: ia_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - scipy
  - scikit-image
  - tifffile
  - jupyterlab
  - openpyxl
  - pyqt  # Required for napari GUI
  - pip
  - pip:
      - "napari[all]"  # Ensures full installation of napari
      - pyclesperanto_prototype